apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: health-check-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Scaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        
        # Resource allocation
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        
        # Timeout configuration
        run.googleapis.com/timeout: "300"
        
    spec:
      # Container concurrency
      containerConcurrency: 100
      
      # Timeout for requests
      timeoutSeconds: 300
      
      # Service account
      serviceAccountName: evolveyou-health-check-service@evolveyou-prod.iam.gserviceaccount.com
      
      containers:
      - name: health-check-service
        image: us-central1-docker.pkg.dev/evolveyou-prod/evolveyou-containers/health-check-service:latest
        
        ports:
        - name: http1
          containerPort: 8080
          
        env:
        - name: SERVICE_NAME
          value: "health-check-service"
        - name: SERVICE_VERSION
          value: "1.0.0"
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLOUD_PROJECT
          value: "evolveyou-prod"
        - name: ENVIRONMENT
          value: "production"
        - name: AUTH_SERVICE_URL
          value: "https://auth-service-hash-uc.a.run.app"
        - name: USER_SERVICE_URL
          value: "https://user-service-hash-uc.a.run.app"
        - name: WORKOUT_SERVICE_URL
          value: "https://workout-service-hash-uc.a.run.app"
        - name: NOTIFICATION_SERVICE_URL
          value: "https://notification-service-hash-uc.a.run.app"
          
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
            
        # Startup probe
        startupProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

